#!/bin/bash
echo "=========================================================="
echo "   CCL Guard - Docker Automated Setup Wizard              "
echo "=========================================================="
echo ""
echo "This wizard will securely configure your API keys and launch the SOC."
echo "Your keys will be saved locally in '.env' and NEVER uploaded anywhere."
echo ""

# Initialize .env file
echo "# Auto-generated by setup_docker.sh" > .env

# AI Engine
echo "--- 🧠 AI Remediation Engine ---"
read -p "Enter your Gemini/OpenAI API Key (Required for AI Analysis): " ai_key
echo "GEMINI_API_KEY=$ai_key" >> .env
echo "OPENAI_API_KEY=$ai_key" >> .env
echo ""

# Twilio
echo "--- 📱 WhatsApp/SMS Alerts (Optional) ---"
read -p "Enter Twilio Account SID (Leave blank to skip): " twilio_sid
if [ -n "$twilio_sid" ]; then
    read -p "Enter Twilio Auth Token: " twilio_token
    read -p "Enter Target Phone Number (e.g. +1234567890): " phone_num
    
    echo "TWILIO_ACCOUNT_SID=$twilio_sid" >> .env
    echo "TWILIO_AUTH_TOKEN=$twilio_token" >> .env
    echo "TWILIO_WHATSAPP_ID=whatsapp:+14155238886" >> .env
    echo "ADMIN_WHATSAPP=$phone_num" >> .env
    echo "✅ Twilio Configured."
else
    echo "⏭️  Skipped Twilio configuration."
fi
echo ""

echo "--- 📧 Email Alerts (Optional) ---"
read -p "Do you want to enable automatic email alerting? (y/n): " email_choice
if [ "$email_choice" == "y" ]; then
    read -p "Enter Sender Email (e.g. alert@company.com): " email_from
    read -p "Enter Email Password / App Password: " email_pass
    read -p "Enter Destination Email for Alerts: " email_to
    
    echo "EMAIL_FROM=$email_from" >> .env
    echo "EMAIL_PASS=$email_pass" >> .env
    echo "EMAIL_TO=$email_to" >> .env
    echo "✅ Email Alerts Configured."
else
    echo "⏭️  Skipped Email configuration."
fi
echo ""

echo "=========================================================="
echo " 🚀 Launching CCL Guard via Docker Compose...             "
echo "=========================================================="

if ! command -v docker-compose &> /dev/null; then
    echo "❌ Error: docker-compose is not installed. Please install Docker."
    exit 1
fi

docker-compose up -d --build

echo ""
echo "✅ Deployment Complete! Both the Director and Client are now running securely."
