import os
import time
import sqlite3
import datetime

try:
    import requests
except ImportError:
    requests = None

from core.database import insert_log, DB_NAME, create_incident

def azure_worker():
    """Background thread to poll Microsoft Defender for Cloud alerts using Microsoft Graph API."""
    tenant_id = os.environ.get("AZURE_TENANT_ID")
    client_id = os.environ.get("AZURE_CLIENT_ID")
    client_secret = os.environ.get("AZURE_CLIENT_SECRET")
    
    if not tenant_id or not client_id or not client_secret or not requests:
        return # Missing credentials, exit silently
        
    print("[Azure Defender] Sync worker initialized.")
    processed_alert_ids = set()

    def get_token():
        token_url = f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"
        data = {
            "grant_type": "client_credentials",
            "client_id": client_id,
            "client_secret": client_secret,
            "scope": "https://graph.microsoft.com/.default"
        }
        resp = requests.post(token_url, data=data)
        if resp.status_code == 200:
            return resp.json().get("access_token")
        return None

    while True:
        try:
            token = get_token()
            if not token:
                time.sleep(300)
                continue
                
            headers = {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json"
            }
            
            # Query Security Alerts via MS Graph
            # Filter for High severity alerts generated recently
            time_filter = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=24)).strftime("%Y-%m-%dT%H:%M:%SZ")
            graph_url = f"https://graph.microsoft.com/v1.0/security/alerts_v2?$filter=severity eq 'high' and createdDateTime ge {time_filter}"
            
            response = requests.get(graph_url, headers=headers, timeout=10)
            
            if response.status_code == 200:
                alerts = response.json().get("value", [])
                
                new_alerts = [a for a in alerts if a.get("id") not in processed_alert_ids]
                
                if new_alerts:
                    con = sqlite3.connect(DB_NAME)
                    
                    for alert in new_alerts:
                        # Extract data from MS Graph Alert representation
                        title = alert.get("title", "Azure Security Alert")
                        desc = alert.get("description", "")
                        sev = alert.get("severity", "High").capitalize()
                        
                        risk = 85
                        if sev == "Critical":
                            risk = 95
                            
                        # Try to get bad IP actor
                        ip = "Azure"
                        evidence = alert.get("evidence", [])
                        for ev in evidence:
                            if ev.get("@odata.type") == "#microsoft.graph.security.ipEvidence":
                                ip = ev.get("ipAddress", "Azure")
                                break

                        insert_log(ip, desc[:200], title, sev, risk)
                        if risk >= 80:
                            create_incident(ip, title, sev, "Alert generated by Microsoft Defender.", "Review Azure Portal.")
                            
                        processed_alert_ids.add(alert.get("id"))
                    
                    con.close()
                    print(f"[Azure Defender] Processed {len(new_alerts)} alerts.")
                    
        except Exception as e:
            print(f"[Azure Defender] Error polling alerts: {e}")
            
        time.sleep(300) # Poll every 5 minutes
